name: tomfrazier
favicon: null
layout_spectrum: 0.4656147214118391
typography_spectrum: 0.12000089837238193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8006126997061074
  lightness: 0.3633498679846525
  saturation: 0.5768008064478636
  rhythmicContrast: 0.9217625996097922
purpose: []
